package com.jr12221.frcdatawizard;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jack
 */
public class ApiEnterForm extends javax.swing.JFrame {

    /**
     * Creates new form apiAsk
     */
    public ApiEnterForm() {
        initComponents();
    }

    public int cleanHints() {
        if (usernameField.getText().equals(ttUsername)) {
            usernameField.setText("");
        }
        if (keyField.getText().equals(ttKey)) {
            keyField.setText("");
        }
        return 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new HintJObject(ttUsername);
        keyField = new HintJObject(ttKey);
        frcSave = new javax.swing.JButton();
        ftcSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(550, 650));

        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        keyField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        frcSave.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        frcSave.setText("Save FRC Key");
        frcSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frcSaveActionPerformed(evt);
            }
        });

        ftcSave.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        ftcSave.setText("Save FTC Key");
        ftcSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftcSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frcSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftcSave))
                    .addComponent(keyField)
                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frcSave)
                    .addComponent(ftcSave))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frcSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frcSaveActionPerformed
        cleanHints();
        PreferenceReadWrite pref1 = new PreferenceReadWrite();
        int code = pref1.AddKeyNoInt(usernameField.getText(), keyField.getText(), false);
        if (code == 0) {
            Call call1 = new Call();
            String callReturn = call1.caller("https://frc-api.firstinspires.org/v2.0/2019/teams?teamNumber=1", false, Main.FRC_BASE);
            if (callReturn == null) {
                MessageDialog.main("Your key may be incorrect or expired.  Try entering it again.");
            } else {
                MessageDialog.main("API Key Code Working!");
            }
        }
        if (code == -2) {
            MessageDialog.main("I/O Error, does your $HOME have write permissions?");
        }
        dispose();

    }//GEN-LAST:event_frcSaveActionPerformed

    private void ftcSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftcSaveActionPerformed
        cleanHints();
        PreferenceReadWrite pref1 = new PreferenceReadWrite();
        int code = pref1.AddKeyNoInt(usernameField.getText(), keyField.getText(), true);
        if (code == 0) {
            Call call1 = new Call();
            String callReturn = call1.caller("https://ftc-api.firstinspires.org/v2.0/2019/teams?teamNumber=7244", false, Main.FTC_BASE);
            if (callReturn == null) {
                MessageDialog.main("Your key may be incorrect or expired.  Try entering it again.");
            } else {
                MessageDialog.main("API Key Code Working!");
            }
        }
        if (code == -2) {
            MessageDialog.main("I/O Error, does your $HOME have write permissions?");
        }
        dispose();

    }//GEN-LAST:event_ftcSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApiEnterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApiEnterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApiEnterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApiEnterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ApiEnterForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton frcSave;
    private javax.swing.JButton ftcSave;
    private javax.swing.JTextField keyField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

    private final String ttUsername = "Enter Username Here";
    private final String ttKey = "Enter Key Here";
}
